export type Role =
  | 'Super Admin'
  | 'Owner'
  | 'Branch Manager'
  | 'Receptionist'
  | 'Trainer'
  | 'Dietitian'
  | 'Accountant'
  | 'Employee'
  | 'Member';

// App Login Credentials — auto-generated by admin
export interface AppUser {
  id: string;
  username: string;         // auto-generated e.g. MEM00125
  email?: string;           // email address or internal auth email
  password?: string;        // temporary or hashed password
  role: Role;
  linkedId: string;         // memberId or employeeId
  linkedName: string;
  branchId: BranchId;
  createdAt: string;
  createdByAdminId: string;
  isActive: boolean;
  mustChangePassword?: boolean;
  tempPassword?: string;
  whatsappStatus?: 'NOT_SENT' | 'SENDING' | 'SENT' | 'DELIVERED' | 'FAILED';
  whatsappSentAt?: string;
  lastLoginAt?: string;
  lastPasswordResetAt?: string;
  permissions: {
    canViewDashboard: boolean;
    canEditWorkouts: boolean;
    canEditDiets: boolean;
    canViewMembers: boolean;
    canManageFinance: boolean;
    canAccessAdmin: boolean;
  };
}

export type BranchId = 'branch-1' | 'branch-2' | 'branch-3';

export type GoalType = 'Weight Loss' | 'Muscle Building' | 'Body Recomposition' | 'Endurance & Cardio' | 'Rehab & Mobility';

export interface Branch {
  id: BranchId;
  name: string;
  code: string;
  city: string;
  address: string;
  phone: string;
  activeMembers: number;
  currentCheckIns: number;
  monthlyRevenue: number;
  capacity: number;
  manager: string;
}

export interface Member {
  id: string;
  membershipNo: string;
  name: string;
  photoUrl: string;
  faceEnrolled: boolean;
  faceIdEnrolled?: boolean;
  mobile: string;
  email: string;
  dob: string;
  gender: 'Male' | 'Female' | 'Other';
  heightCm: number;
  weightKg: number;
  startWeightKg: number;
  bmi: number;
  chestCm: number;
  waistCm: number;
  armsCm: number;
  thighsCm: number;
  bloodGroup: string;
  emergencyContactName: string;
  emergencyMobile: string;
  address: string;
  medicalHistory: string;
  goal: GoalType;
  referralSource: string;
  branchId: BranchId;
  planId: string;
  planName: string;
  startDate: string;
  endDate: string;
  expiryDate?: string;
  status: 'Active' | 'Expiring Soon' | 'Expired' | 'Cancelled' | 'Renewal Due' | 'Suspended' | 'Pending Payment';
  assignedTrainerId?: string;
  assignedDietitianId?: string;
  rewardPoints: number;
  referralCode: string;
  pendingDues: number;
  paidAmount?: number;
  totalPlanAmount?: number;
  lastPaymentDate?: string;
  nextDueDate?: string;
  paymentStatus?: 'Paid' | 'Partially Paid' | 'Pending' | 'Overdue';
  lockerNumber?: string;
  userId?: string;
  username?: string;
  tempPassword?: string;
  mustChangePassword?: boolean;
  whatsappStatus?: 'NOT_SENT' | 'SENDING' | 'SENT' | 'DELIVERED' | 'FAILED';
  whatsappSentAt?: string;
  lastLoginAt?: string;
  lastPasswordResetAt?: string;
}

export interface AuditLog {
  id: string;
  eventType:
    | 'MEMBER_CREATED'
    | 'ACCOUNT_PROVISIONED'
    | 'PASSWORD_RESET'
    | 'WHATSAPP_SENT'
    | 'WHATSAPP_FAILED'
    | 'ACCOUNT_DISABLED'
    | 'ACCOUNT_ENABLED'
    | 'FIRST_LOGIN_COMPLETED'
    | 'PASSWORD_CHANGED';
  memberId: string;
  memberName: string;
  actorId: string;
  actorRole: Role;
  details: string;
  timestamp: string;
  status: 'SUCCESS' | 'FAILED';
}

export interface MembershipPlan {
  id: string;
  name: string;
  durationMonths: number;
  durationDays?: number;
  duration?: 'Monthly' | 'Quarterly' | 'Half-Yearly' | 'Yearly' | 'Custom';
  basePrice: number;
  joiningFee: number;
  gstPercent: number;
  totalPrice: number;
  description?: string;
  includedAddons: string[];
  includedFeatures?: {
    personalTraining: boolean;
    dietPlan: boolean;
    locker: boolean;
    steam: boolean;
    [key: string]: boolean | undefined;
  };
  branchId?: BranchId;
  pricePerBranch?: any;
  isActive?: boolean;
  isPopular?: boolean;
}

export interface AttendanceRecord {
  id: string;
  memberId: string;
  memberName: string;
  memberPhoto: string;
  branchId: BranchId;
  entryTime: string;
  exitTime?: string;
  verificationMethod: 'Dynamic QR' | 'Face ID' | 'Manual Override';
  deviceInfo: string;
  date: string;
  status: 'Active In Gym' | 'Checked Out';
}

export interface Exercise {
  id: string;
  name: string;
  category: 'Chest' | 'Back' | 'Legs' | 'Shoulders' | 'Arms' | 'Core' | 'Cardio';
  targetSets: number;
  targetReps: number;
  weightKg: number;
  restSeconds: number;
  videoUrl?: string;
  notes?: string;
  completed: boolean;
}

export interface DailyWorkoutSplit {
  day: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
  title: string;
  exercises: Exercise[];
}

export interface WeeklyWorkoutPlan {
  weekNumber: number;
  weekTitle: string;
  splits: DailyWorkoutSplit[];
}

export interface WorkoutPlan {
  id: string;
  memberId: string;
  weeklyPlans: WeeklyWorkoutPlan[];
  updatedAt: string;
}

export interface MealItem {
  id: string;
  name: string;
  portion: string;
  calories: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  completed: boolean;
}

export interface MonthlyDietPlan {
  monthNumber: number;
  monthTitle: string;
  targetCalories: number;
  targetProteinG: number;
  targetCarbsG: number;
  targetFatG: number;
  waterTargetLiters: number;
  meals: {
    breakfast: MealItem[];
    lunch: MealItem[];
    snack: MealItem[];
    dinner: MealItem[];
  };
}

export interface DietPlan {
  id: string;
  memberId: string;
  monthlyPlans: MonthlyDietPlan[];
  waterCurrentLiters: number;
}

export interface ProgressMetric {
  id: string;
  memberId: string;
  date: string;
  weightKg: number;
  bodyFatPercent: number;
  chestCm: number;
  waistCm: number;
  armsCm: number;
  photoBeforeUrl?: string;
  photoAfterUrl?: string;
}

export interface Lead {
  id: string;
  name: string;
  mobile?: string;
  phone?: string;
  email: string;
  source: 'Walk-in' | 'Instagram Ad' | 'Website' | 'Member Referral' | 'Instagram';
  goal?: string;
  interestGoal?: string;
  assignedStaffId?: string;
  assignedStaffName?: string;
  assignedStaff?: string;
  branchId: BranchId;
  stage: 'Walk-in' | 'Interested' | 'Trial Scheduled' | 'Joined' | 'Lost';
  followUpDate: string;
  notes: string;
}

export interface Employee {
  id: string;
  name: string;
  photoUrl: string;
  role: Role;
  mobile: string;
  phone?: string;
  specialization?: string;
  email: string;
  branchId: BranchId;
  baseSalary: number;
  ptCommissionRate: number;
  ptSessionsCompleted: number;
  joiningDate: string;
  shift: string;
  attendanceDays: number;
}

export interface SupplementProduct {
  id: string;
  name: string;
  barcode: string;
  category: 'Protein' | 'Pre-Workout' | 'Creatine' | 'Vitamins' | 'Accessories';
  price: number;
  stockQty: number;
  imageUrl: string;
  image?: string;
  brand?: string;
  gstPercent: number;
}

export interface LockerItem {
  id: string;
  lockerNumber: string;
  branchId: BranchId;
  occupiedByMemberId?: string;
  occupiedByMemberName?: string;
  assignedMemberName?: string;
  status: 'Available' | 'Occupied' | 'Under Maintenance';
  assignedDate?: string;
  expiryDate?: string;
}

export interface ComplaintTicket {
  id?: string;
  memberId?: string;
  memberName?: string;
  memberOrStaffName?: string;
  role?: string;
  title?: string;
  branchId: BranchId;
  category: 'Equipment Maintenance' | 'Cleanliness' | 'Trainer Conduct' | 'Billing / Refund' | 'AC / Ventilation' | 'Machine Broken';
  description: string;
  createdAt?: string;
  status?: 'Open' | 'In Progress' | 'Resolved';
  priority?: string;
}

export interface SystemNotification {
  id: string;
  targetRole: Role | 'All';
  memberId?: string;
  title: string;
  message: string;
  timestamp: string;
  type: 'security' | 'workout' | 'diet' | 'billing' | 'lead' | 'system' | 'general' | 'reminder';
  read: boolean;
}

export interface Transaction {
  id: string;
  memberId: string;
  memberName: string;
  branchId: BranchId;
  amount: number;
  paymentMethod: 'Cash' | 'UPI' | 'Card' | 'Bank Transfer' | 'NetBanking' | 'Cheque';
  category: 'Membership Dues' | 'PT Package' | 'Supplement Sale' | 'Locker Rent' | 'Other Income';
  date: string;
  receiptNo: string;
  planName?: string;
  notes?: string;
}

export interface Expense {
  id: string;
  name: string;
  category: string; // e.g. Salary, Rent, Electricity, Water, Internet, Equipment, Equipment Repair, Maintenance, Cleaning, Marketing, Software, Subscription, Office Supplies, Transportation, Utilities, Other
  amount: number;
  date: string;
  paymentMethod: 'Cash' | 'UPI' | 'Card' | 'Bank Transfer' | 'NetBanking' | 'Cheque';
  description?: string;
  receiptUrl?: string;
  createdBy?: string;
  branchId: BranchId;
  status: 'Paid' | 'Pending' | 'Cancelled';
}

export interface ExpenseType {
  id: string;
  name: string;
  description?: string;
  isDefault?: boolean;
  color?: string;
}

export interface WebsiteCustomer {
  id: string;
  name: string;
  email: string;
  phone: string;
  registeredDate: string;
  trialPassUsed: boolean;
  activePassName?: string;
  bookedClasses: {
    id: string;
    className: string;
    instructor: string;
    dateTime: string;
    branchName: string;
    status: 'Confirmed' | 'Completed' | 'Cancelled';
  }[];
  purchasedPasses: {
    id: string;
    passName: string;
    purchaseDate: string;
    expiryDate: string;
    price: number;
    qrToken: string;
    status: 'Active' | 'Used' | 'Expired';
  }[];
}

